services:
  simple-apps:
    container_name: ct-simpleapps
    image: dindarestika/simpleapps
    ports:
      - "8181:3000"
    environment:
      - DB_NAME=training
      - DB_HOST=172.23.0.95
      - DB_USER=peserta
      - DB_PASS=password
      - APP_PORT=3000
    restart: always